### ISSUE TITLE
Name display consistency

### ISSUE THREAD

**Issue by mwjames** [TobiasWeller/SemanticImageAnnotator#4]
https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Pages_sp%C3%A9ciales

![image](https://cloud.githubusercontent.com/assets/1245473/26761481/3565c958-496b-11e7-9f91-d351a045876d.png)

**Comment by TobiasWeller** [comment]
This issue is solved in the new Verison.
