### ISSUE TITLE
Anon user is allowed to install?

### ISSUE THREAD

**Issue by mwjames** [TobiasWeller/SemanticImageAnnotator#5]
https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticImageAnnotator

![image](https://cloud.githubusercontent.com/assets/1245473/26761495/7bc1ed32-496b-11e7-9b47-8fb9ea6f5ea7.png)

PS: What happens when I press install? What is installed? Why is it necessary? Some explanatory text would be much appreciated before hacking the keyboard.

**Comment by TobiasWeller** [comment]
Ok., very nice idea. I changed it, so only sysops users can access this Special Page.
I will add some more information in order to explain the progress.

Cheers
Tobi
