### ISSUE TITLE
Special:SemanticImageAnnotator

### ISSUE THREAD

**Issue by D-Groenewegen** [TobiasWeller/SemanticImageAnnotator#6]
Hi Tobias,

Thanks a lot, first of all, for reviving this extension and improving on it! 

My 2 cents. The list of forms given on Special:SemanticImageAnnotator appears to be limited to no more than 10. See https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticImageAnnotator for an example where this becomes a problem.

**Comment by TobiasWeller** [comment]
Hello,

thanks for reporting this issue. I had a look on it. I perform a Query on the MediaWiki API (without specifying a limit value). The default value is set on 10 items to be retrieved[1]. Therefore, only 10 Forms are shown. I will increase the number of retrieved Forms by this query and upload an updated version.

Thank you very much!


Cheers
Tobi

[1] https://www.mediawiki.org/wiki/API:Query

**Comment by TobiasWeller** [comment]
Ok., I just changed the aplimit. So now more Formulars in SpecialPage are received.
Thanks for your comment!

Cheers
Tobi
